# Generated by Django 2.2.28 on 2025-03-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('threadID', models.AutoField(primary_key=True, serialize=False)),
                ('threadPhoto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32)),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('profilePictureURL', models.URLField()),
                ('password', models.CharField(max_length=128)),
                ('follows', models.ManyToManyField(blank=True, to='Threadly.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=1000)),
                ('photoContent', models.URLField()),
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Threadly.User')),
                ('threadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Threadly.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.TextField(max_length=100)),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Threadly.Post')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Threadly.User')),
            ],
        ),
    ]
