# Generated by Django 2.2.28 on 2025-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threadly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
