# Generated by Django 2.2.28 on 2025-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threadly', '0002_auto_20250323_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
