# Generated by Django 2.2.28 on 2025-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threadly', '0008_auto_20250323_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, unique=True)),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('profilePictureURL', models.URLField()),
                ('password', models.CharField(default='defaultpassword', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('follows', models.ManyToManyField(blank=True, to='Threadly.Thread')),
            ],
        ),
    ]
