# Generated by Django 2.2.28 on 2025-03-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Threadly', '0010_auto_20250323_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
